#!/usr/bin/env bash
#script thatpings an ip address passed as an argument
#it accepts a string as an argument
#ping the ip 5 times

if [ "$#" -eq 0 ];
then
echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
ping -c 5 "$1"
fi
