#!/usr/bin/env bash
#script that creates the file "/var/run/myscript.pid containing its pid
#displays to infinity and beyond indefinatly,
#displays i hate the kill command when receiving a SIGTERM signal
#displays y u no love mr?! when receiving a SIGINT signal
#deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

file=/var/run/myscript.pid
echo $$ > "$file"

while true
do
echo "To infinity and beyond"
sleep 2

trap 'echo "Y U no love me?!"' SIGINT
trap 'rm $file; exit' SIGQUIT
trap 'echo Ihate the kill command; rm $file; exit' SIGTERM
done
