#!/usr/bin/env bash
#script that displays, to infinity and beyond with sleep 2 in between each iteration
#i am invincible!!! when reciving a sigterm signal

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
