#!/usr/bin/env bash
#script that displays the contents fo the file /etc/passwd, should only display username, usr id, home dir path for the user

while read -r passwd; do
echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
