#!/usr/bin/env bash
#script that prints Best School 10 times but between 8 and 10 we add hi

k=0

while (( k < 11 ))
do
	if (( k == 9 ))
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((k++))
done
