#!/usr/bin/env bash
#script that displays the time for 12hours and 59minutes, hours from 0 to 12 minutes from 1 to 59

hour="0"

while [ $hour -lt 12 ]
do
echo "Hour: $hour"
while [ $minute -lt 60 ]
do
echo "$minute"
((minute++))
done
((hour++))
minute="1"
done
