#!/usr/bin/env bash
#install ufw firewall and set requirements

#update,install and enable ufw

sudo apt-get update
sudo apt-get install ufw
sudo ufw enable

#set default policies
sudo ufw default deny incomming

# allow specific ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

#enforce the rules and check status
sudo ufw enable
sudo ufw status
