#!/usr/bin/env bash
#script that configures an ubuntu server with this requrements
#localhost resolves to 127.0.02
#facebook.com resolve to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebool.com" >> ~/hosts.new
cp -f ~/host.new /etc/hosts
